### ISSUE TITLE
z1 should exit if an error occurs

### ISSUE THREAD

**Issue by steebchen** [robojones/z1#1]
When an error happens before the `z1 start ..` command is successful, the command should return the error and exit with status code 1. I do see the error in the logs, but z1 just waits endlessly since my app.listen returned an error.

**Comment by robojones** [comment]
Can your give me further information?
I wasn't able to recreate the situation your described.

**Comment by steebchen** [comment]
I think I only output something to stderr instead of throwing an error. May that be the issue?

**Comment by robojones** [comment]
If you want to be sure you can try:
```javascript
process.exit(1)
```

**Comment by steebchen** [comment]
Yep, that's the issue. Thanks for your help, I will use a different method to output errors.
